version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install -r requirements.txt
      - pip install pytest-django
  build:
    commands:
      - python app/manage.py test
